---
kind: pipeline
type: docker
name: runner-checks

steps:
- name: able-to-pull-images-and-execute
  image: docker:latest
  commands:
  - echo '[INFO] Running from within pipeline container'

trigger:
  branch:
    - master
    - develop
    - feature/*
    - bugfix/*
